##Tabela de embarcador

embarcador_multi = [
    'MULTILASER INDUSTRIAL S.A.'
]

##Tabela de ocorrencias
ocorrencias_agendamento_em_aberto = [
    'Coleta Encaminhada Para Reagendamento',
    'A Reagendar',
    'A agendar',
    'Transcrição da Conversa',
    'Agendamento dedicado',
    'Entrega Agendada com o Cliente'
]

aguardando_check_list =[
    'Aguardando Check List'
]

agendamento_em_aberto = [
    'A agendar',
    'A Reagendar',
    'Coleta Encaminhada Para Reagendamento',
    'Entrega Agendada com o Cliente',
    'Agendamento dedicado',
    'Transcrição da Conversa'
]

cancelado_finalizado = [
    'Cancelar solicitação de coleta',
    'Finalizado - Nova coleta gerada',
    'Coleta Cancelada'
]

coleta_em_aberto =[
    'Agendado',
    'AGUARDANDO NFD DE TROCA CASADA',
    'Area de Risco',
    'Atualização',
    'Coleta  Realizada Informada Pelo Motorista',
    'Coleta realizada normalmente',
    'Cotação Para Coleta',
    'Em Rota de Coleta Reversa',
    'Em Rota de Planejamento',
    'Falta de Tempo Hábil',
    'Programado Para Coleta Reversa',
    'Quebra do Veiculo',
    'Bau Cheio'
]

devolucao_em_aberto=[
    'Aguardando Autorização de Grade',
    'Chegada na Cidade ou Filial de Destino',
    'Chegada na Unidade de Devolução',
    'Chegada na Unidade de Transferência',
    'Chegada prevenção de perdas',
    'Coleta Realizada Informada Pelo Motorista',
    'Despacho Realizado',
    'Devolução não Autorizada pelo Cliente',
    'Em Rota de Despacho',
    'Em Rota de Devolução',
    'Em Rota de Retira',
    'Nota Fiscal Retida pela Fiscalização',
    'Produto Coletado',
    'Programado Para Despacho',
    'Programado para Devolução',
    'Programado Para Retira',
    'Programado Para Transferencia',
    'Recebido no CD da Transportadora',
    'Saida da Unidade',
    'Tratativa de Coleta de Loja',
    'Volume não Recebido',
    'Volumes Localizados'
]

devolvido=[
    'Devolução Realizada Normalmente',
    'Entrega Realizada Normalmente',
    'Mercadoria Devolvida ao Cliente de Origem'
]

entrega_em_aberto =[
    'Entrega Reagendada com o Cliente'
]


ocorrencias_insucesso_de_agendamento = [
    'telefones inválidos - parceiros',
    'Telefones Inválidos',
    'Chamada Não Atendida',
    'Insucesso de Agendamento - Cliente Recusou a Coleta do Produto',
    'Insucesso de Agendamento - Cliente Informa que já Devolveu o Produto',
    'Insucesso de Agendamento - Produto Inadequado',
    'Chamada não atendida - parceiros',
    'Insucesso de Agendamento - Cliente vai Ficar com Produto',
    'Telefone não atendido - parceiro'
]

correncia_insucesso_de_devolucao = [
    'Falta de tempo no recebimento cliente',
    'Recusa por produto divergente',
    'Recusa por produto avariado',
    'Recusa por não agendamento',
    'Recusa por falta de volumes',
    'Recusa por documentação Incompleta',
    'Produto não apresentado',
    'Recusa por Falta de Pedido de Compra'
]

outros = [
    'Aeroporto fechado na origem',
    'Aeroporto fechado no destino',
    'Agendado VIA APP',
    'Cliente Destino em Greve',
    'Cliente Destino Encerrou Atividades',
    'Cliente Destino não Recebe Pedido Parcial',
    'Cliente Destino só Recebe Pedido Parcial',
    'Cliente Destino somente Recebe Mercadoria com Frete Pago',
    'Cliente Fechado para Balanço',
    'Data de Entrega Diferente do Pedido',
    'Devolução com cobrança do cliente',
    'Em Rota de Entrega',
    'Entrega com Indenização Efetuada',
    'Excesso de Carga/Peso',
    'Excesso de Veículos',
    'Falta com Solicitação de Reposição',
    'Feriado Local/Nacional',
    'Férias Coletivas',
    'Funcionário não autorizado a Receber Mercadorias',
    'Greve Nacional (Greve Geral)',
    'Informações Adicionais XML/EDI',
    'Informações de Contato',
    'Mercadoria em Desacordo com o Pedido Compra',
    'Mercadoria em poder da SUFRAMA para Internação',
    'Mercadoria Embarcada para Rota Indevida',
    'Mercadoria fora da Embalagem Especificada',
    'Mercadoria Recusada pelo Cliente',
    'Mercadoria Redespachada (Entregue para Redespacho)',
    'Mercadoria reentregue ao cliente destino',
    'Mercadoria retida ate segunda ordem',
    'Mercadoria Retirada da cia aérea',
    'Mercadoria Retirada para Conferência',
    'Nota Fiscal com Produtos de Setores Diferentes',
    'Pedido de Compra Incompleto',
    'Preço Mercadoria em Desacordo com o Pedido Compra',
    'Problemas Fiscais',
    'Produto Sem Embalagem',
    'Programado para Entrega',
    'Redespacho não Indicado',
    'Redespacho somente com Frete Pago',
    'Reentrega com Cobrança do Cliente',
    'Reversa Agendamento com cliente',
    'REVERSA RECEBIDA NO CD',
    'SKU / Produto',
    'Solicitacao Recebida',
    'teste teste',
    'Transferencia de Devolução Pendente',
    'Transportadora não Atende a Cidade da Transportadora de Redespacho',
    'Transportadora não Atende a Cidade do Cliente Destino',
    'Voo cancelado'
    
]

pendecia = [
    'Liberado da Pendência para Galpão 1',
    'Falta com Busca/Reconferência',
    'Liberado da Pendencia para Devolução BR',
    'Liberado da Pendencia para Devolução GRU',
    'Liberado para reagendamento (SEM RECALCULAR PRAZO)',
    'Liberado da Pendencia para Devolução RJO',
    'Liberado da Pendencia para Devolução BHZ',
    'Agendamento Liberado pelo Cliente',
    'Liberado para Indenizar',
    'Pendência em Tratativa',
    'Pendência em tratativa - Transferência',
    'Pendência em tratativa MG',
    'Pendência em tratativa RJ',
    'Tratativa inventário',
    'Pendência em Tratativa - SSA',
    'Liberado da Pendencia - SSA',
    'Pendência em tratativa REC',
    'Chegada na Unidade de Reparo',
    'Liberado da pendência para devolução REC',
    'Pendência em tratativa JPA',
    'Pendência em tratativa FOR',
    'Liberado da pendência para devolução FOR',
    'Pendência em tratativa THE',
    'Liberado da pendência para devolução JPA',
    'Liberado da pendência para devolução SLZ',
    'Pendência em tratativa NAT',
    'Liberado da pendência para devolução NAT'
]

ocorrencia_insucesso_de_coleta = [
    'No Show',
    'Estabelecimento Fechado',
    'Endereço Sem Acesso',
    'Quantidade de Produto em Desacordo com NF',
    'Cliente Mudou de Endereço',
    'Item Divergente da Nota Fiscal',
    'Produto Montado',
    'Produto Indisponível Para Coleta',
    'Cliente Ausente 1. Tentativa',
    'Cliente Ausente 2. Tentativa',
    'Cliente Ausente 3. Tentativa',
    'Cliente Ausente',
    'Cliente Ficara com o Produto',
    'Cliente Solicita Troca Casada',
    'Cliente Informa que já Devolveu o Produto',
    'Mudança de Endereço',
    'Cliente Recusou Coleta do Produto',
    'Item Divergente do Check List',
    'Pessoa Desconhecida',
    'Estrada/Entrada de Acesso Interditada',
    'Endereço Não Localizado',
    'Recusa por Pedido de Compra Cancelado',
    'Cliente Ausente 4. Tentativa',
    'Entrega Prejudicada pela Chuva'
]

ocorrencias_coleta_em_aberto =[
    'Coleta  Realizada Informada Pelo Motorista',
    'Bau Cheio',
    'Quebra do Veiculo',
    'Falta de Tempo Hábil',
    'Coleta realizada normalmente',
    'Area de Risco',
    'Em Rota de Planejamento',
    'Atualização',
    'Agendado',
    'Programado Para Coleta Reversa',
    'Cotação Para Coleta',
    'AGUARDANDO NFD DE TROCA CASADA'
]

ocorrencia_devolucao_em_aberto = [
    'Volumes Localizados',
    'Volume não Recebido',
    'Tratativa de Coleta de Loja',
    'Saida da Unidade',
    'Programado Para Retira',
    'Programado para Devolução',
    'Programado Para Despacho',
    'Produto Coletado',
    'Em Rota de Retira',
    'Em Rota de Devolução',
    'Em Rota de Despacho',
    'Em Rota de Coleta Reversa',
    'Devolução não Autorizada pelo Cliente',
    'Despacho Realizado',
    'Coleta Realizada Informada Pelo Motorista',
    'Chegada prevenção de perdas',
    'Chegada na Unidade de Transferência',
    'Chegada na Unidade de Devolução',
    'Chegada na Cidade ou Filial de Destino',
    'Aguardando Autorização de Grade',
    'Nota Fiscal Retida pela Fiscalização',
    'Programado Para Transferencia',
    'Recebido no CD da Transportadora'
]

clientes = [
    {'nome':'CARREFOUR', 'raiz_cnpj':'45543915'},
    {'nome':'MULTI B2C', 'raiz_cnpj':'59717553'},
    {'nome':'KABUM', 'raiz_cnpj':'05570714'},
    {'nome':'MADEIRAMADEIRA', 'raiz_cnpj':'10490181'},
    {'nome':'MADESA', 'raiz_cnpj':'89042642'},
    {'nome':'MAGAZINE 1P', 'raiz_cnpj':'47960950'},
    {'nome':'SAMSUNG', 'raiz_cnpj':'00280273'},
    {'nome':'SAMSUNG', 'raiz_cnpj':'12241369'},
    {'nome':'GRUPO CASAS BAHIA', 'raiz_cnpj':'33041260'},
    {'nome':'MVX', 'raiz_cnpj':'08215490'},
    {'nome':'GAZIN', 'raiz_cnpj':'22962737'},
    {'nome':'GAZIN', 'raiz_cnpj':'77941490'},
    {'nome':'ELETRORARO', 'raiz_cnpj':'05965548'},
    {'nome':'ENGAGE', 'raiz_cnpj':'24867555'},
    {'nome':'ELEMENTS', 'raiz_cnpj':'25098466'},
    {'nome':'SAMSUNG', 'raiz_cnpj':'24574383'},
    {'nome':'MAGAZINE 3P', 'raiz_cnpj':'24230747'},
    {'nome':'DECATHON', 'raiz_cnpj':'02314041'},
    {'nome':'FOX ONLINE', 'raiz_cnpj':'38199480'},
    {'nome':'DEXCO', 'raiz_cnpj':'97837181'},
    {'nome':'ASTRA SA','raiz_cnpj':'50949528001232'}
]

regional_BR = [
    "AJU1 - GC PRESTACAO DE SERVIÇOS GERAIS LTDA",
    "AJU2 - JPS LOGISTICA E TRANSPORTES LTDA",
    "AJU3 - LOGISTICA SERGIPE LTDA",
    "AQA1 - RAPIDAO ARARAQUARA",
    "AQA2 - TIAGO PEREIRA TENORIO 30256426880",
    "ARU2 - JUNIOR TRANSPORTES ARACATUBA EIRELI",
    "BAU1 - ANTONIO CARLOS TORDIVELLI",
    "BEL1 - JM TRANSPORTES E LOGISTICA LTDA",
    "BNU1 - WALDEMAR ROBERTO NICOLODELLI",
    "BRM1 - KZN DIGITAL EXPRESS TRANSPORTE E LOGISTICA LTDA",
    "BRR - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "BRU - RICARDO SILVA DE SANTANA",
    "BSB1 - DF TRANSPORTES E LOGISTICA EIRELI",
    "BSB2 - PLANETA CARGAS E ENCOMENDAS EIRELI",
    "CAC1 - NA-HORA TRANSPORTES LTDA",
    "CAC2 - J. ANDREOLLA E CIA LTDA",
    "CCM1 - ICA LOG TRANSPORTES LTDA",
    "CGB1 - PHEX TRANSPORTE E TURISMO EIRELI ME",
    "CGR1 - PROVEDORA DE TRANSPORTES E LOGISTICA LTDA",
    "CWB1 - DHS EXPRESS CARGAS E ENCOMENDAS LTDA",
    "CWB2 - LONDON",
    "CWB3 - LKW EXPRESS TRANSPORTES LTDA",
    "CWB4 - LOGISTICA E TRANSPORTES SAO LUIZ LTDA",
    "ESTILO EXPRESS TRANSPORTES E SERVIÇOS DE MALOTES LTDA",
    "EUN - PRIME LINE SERVIÇOS DE APOIO ADMINISTRATIVO LTDA",
    "FDS - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "FEC1 - GAMA FSA TRANSPORTES LOG LTDA",
    "FLN1 - SUL CONEXION EXPRESS CARGAS EIRELI",
    "FLN2 - ANJOS COMERCIO E TRANSPORTES LTDA",
    "FLN3 - THUNDERLOG TRANSPORTES EXPRESS LTDA",
    "FND1 - A. N. TRANSPORTES LTDA",
    "FOR1 - GPS EXPRESS LOGISTICA LTDA",
    "FOR2 - SEG EXPRESSO TRANSPORTES LTDA",
    "FOR3 - SGF EXPRESS SERVIÇOS DE TRANSPORTES DE CARGAS LTDA",
    "FOR4 - FORTLOG TRANSPORTES LTDA",
    "FRB1 - EVA ANDREOLLA & FILHOS LTDA",
    "GPB1 - N.N DE ABREU JUNIOR",
    "GYN1 - PLANETA CARGAS E ENCOMENDAS EIRELI - ME",
    "IMP1 - D´MARI - LOCACAO, TRANSPORTES E LOGISTICA LTDA",
    "IMP2 - TEREZINHA DE JESUS TAVARES AMARAL",
    "IRC - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "ITB - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "ITJ1 - MRL LOGISTICA EM DISTRIBUICAO EIRELI",
    "ITJ2 - TEREZINHA APARECIDA PATEL SERVIÇOS DE LOGISTICA LTDA",
    "JCB1 - TRANSPORTES RODOVIARIOS DA COSTA LTDA",
    "JOI2 - LAFFIN LOG TRANSPORTES EIRELI",
    "JPA1 - SANDRO DE LIMA OLIVEIRA",
    "JPA2 - AVEX TRANSPORTE E LOGISTICA LTDA",
    "JPA3 - LAUDEICE ARAUJO DE BRITO",
    "LAJ1 - NAVISTAR LOGISTICA E DISTRIBUICAO LTDA",
    "LAJ2 - DISTRIBUIDORA GRANDE PLANALTO DE PUBLICACOES LTDA",
    "LDB1 - ND CARGAS LTDA",
    "MAB1 - M. L. G. TRANSPORTE EIRELI",
    "MAO1 - BSS SOLUCOES INTEGRADAS",
    "MCP1 - I & I CASCAES LTDA",
    "MCZ1 - MCZ EXPRESS SERVICE LTDA",
    "MGF1 - SOUZA & PRATTO LTDA",
    "MII1 - ISRAEL OLIVEIRA AGIANI 34592973879",
    "MYKAELLA CARVALHO DE ARAUJO 18486068770",
    "N.R. ALVES",
    "NAT1 - SIGA EXPRESS TRANSPORTES DE CARGAS LTDA",
    "NAT2 - TRANSROCHA",
    "NAT3 - AVEX TRANSPORTE E LOGISTICA LTDA",
    "PAF - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "PMW1 - WS EXPRESS TRANSPORTES E SERVIÇOS DE MALOTES LTDA",
    "POA1 - TAC CARGO TRANSPORTE E LOGISTICA LTDA",
    "POA3 - AJ BERLEZI TRANSPORTE",
    "POA4 - JEFERSON RODRIGO PINHEIRO",
    "PPB1 - L R ZANARDI DOS SANTOS TRANSPORTES",
    "PPB2 - CARLOS EDUARDO BRUNO LOPES PINHEIRO 08026674812",
    "PVH1 - GIRASSOL SERVIÇOS E TRANSPORTES EIRELI",
    "RAO1 - DISK JATO ENTREGAS RAPIDAS LTDA",
    "RAO2 - TRANS EXPRESS TRANSPORTE DE CARGAS LTDA",
    "RAO3 - NADIA DE MOURA BULHOES",
    "RBR1 - MARIO DA SILVA OLIVEIRA",
    "REC1 - G. FREIRE BEZERRA DE MORAIS",
    "RJO2 - GABRIEL LESSA GONCALVES 15238157797",
    "RJO2 - ML TRANSPORTES LTDA",
    "RJO3 - BORTOLUZZI E PORTO TRANSPORTES LTDA",
    "RJO4 - PROATIVA ALE TRANSPORTE E LOGISTICA LTDA",
    "RJO5 - AJP TRANSPORTE E LOGISTICA LTDA",
    "SAJ - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "SBA - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "SDS - MARCOS ROBERTO CORREIA LTDA",
    "SJP1 - ART AERO RODOVIARIO TRANSPORTES EIRELI",
    "SJP2 - JJD TRANSPORTES RIO PRETO LTDA",
    "SLZ1 - D´MARI - LOCACAO, TRANSPORTES E LOGISTICA LTDA",
    "SLZ2 - RC EXPRESSO",
    "SQX1 - ZANOTELLI TRANSPORTES & LOGISTICA LTDA",
    "SSA1 - SOMA EXPRESS SERVIÇOS DE ENTREGAS DE MALOTE LTDA",
    "SSA2 - THIAGO BORBA BARROS DE LIMA TRANSPORTES",
    "THE1 - D MARI TRANSPORTES TERESINA LTDA",
    "THE2 - T. N. MARINHO SERVIÇOS DE MALOTE LTDA",
    "THE3 - IMEDIATA TRANSPORTE E LOGISTICA LTDA",
    "THE4 - TRANSBRAGA CARGAS E ENCOMENDAS LTDA",
    "THE5 - J B TRANSPORTE E LOGISTICA LTDA",
    "TRR1 - LDA OPERACOES LOGISTICAS E LOCACAO LTDA",
    "VDC - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "VDC1 - VDC LOG TRANSPORTE E LOGISTICA MULTIMODAL LTDA",
    "VIX1 - SOULOG SOLUCOES EM TRANSPORTES E SERVIÇOS LTDA",
    "VIX2 - NRE TRANSPORTES EIRELI ME",
    "VIX3 - RODOSTAR LOGISTICA E TRANSPORTES EIRELI",
    "XAP1 - JULIO CESAR DA SILVA",
    "XAP1 - MARLI TRANSPORTES EIRELI",
    "XAP2 - E-CARGO EXPRESS LTDA",
    "JCB2 - ABATTI TRANSPORTES E SERVIÇOS LTDA",
    "MAB2 - W R DE ANDRADE RIBEIRO JUNIOR TRANSPORTES",
    "BNU2 - MICHAEL DOS SANTOS",
    "SBS1 - MARCOS ROBERTO CORREIA LTDA",
    "VIX4 - LOGISTICA E TRANSPORTE RODOSTAR CONECCAO ESPIRITO SANTO LTDA",
    "REC3 - A S MENDES TRANSPORTES LTDA",
    "RDS1 - SABINO LOGISTICA LTDA",
    "GPB2 - MARIA JOSE FERREIRA DE ABREU",
    "RDS1 - SABINO LOGISTICA LTDA",
    "BAU2 - ROGERIO CESAR ZAGATTO",
    "RJO6 - AJP TRANSPORTE E LOGISTICA LTDA",
    "CWB5 - GAP CARGO TRANSPORTES LTDA",
    "SSA3 - IRC - ENGAGE TRANSPORTES E SERVIÇOS LOGISTICOS LTDA",
    "MCP2 - J. H. VALENTE SILVA",
    "CWB6 - LTSL BAHIA ENCOMENDAS URGENTES LTDA",
    "MGF2 - M E DOS SANTOS RIBEIRO TRANSPORTES RODOVIARIOS LTDA",
    "FDS2 - LTSL ENCOMENDAS URGENTES LTDA",
    "CGB2 - AGIL SERVIÇOS DE COLETAS E ENTREGAS DE CARGAS E ENCOMENDAS LTDA",
    "TXF1 - JS SOLUCOES LOGISTICA LTDA",
    "BRA1 - ACCERT TRANSPORTES E LOGISTICA LTDA",
    "VDC3 - LMS SERVIÇOS DE TRANSPORTES RODOVIARIOS LTDA",
    "AQA3 - TIAGO TRANSPORTES EXPRESS LTDA",
    "MGF3 - RD-X LOG TRANSPORTES LTDA",
    "SAP1 - RODOLOGCARGAS TRANSPORTADORA LTDA",
    "ITN1 - MG LOG TRANSPORTES LTDA",
    "EDC1 - VTRANS- VINICIUS TRANSPORTES DE CARGAS & SERVIÇOS LTDA",
    "ITN1 - MG LOG TRANSPORTES LTDA",
    "CGB3 - A F TRANSPORTE EXPRESS LTDA",
    "FDS4 - E.L TRANSPORTES E LOGISTICA LTDA",
    "MGU1 - ALDFER TRANSPORTE E LOGISTICA LTDA",
    "SOD1 - SORREG CARGAS E ENCOMENDAS LTDA",
    "PVI1 - SEVEN E CAMPOS TRANSPORTES LTDA",
    "SSZ1 - ARS EXPRESS LTDA",
    "FDS5 - E.L TRANSPORTES E LOGISTICA LTDA",
    "SSZ2 - LAURO WASUKE JANZINI ISHIDA TRANSPORTES",
    "RP DA SILVA EMBALAGENS",
    "TBR1 - DARROITE TRANSPORTES LTDA",
    "CCM2 - JAC TRANSPORTE DE ENCOMENDAS LTDA",
    "CAW1 - RR RODRIGUES TRANSPORTES",
    "MVX - COMERCIO ELETRONICO LTDA",
    "SLZ2 - P. ROOSEVELT DOS REIS CAVALCANTE",
    "SEM AGENTE",
    "TEC1 - R RIBEIRO VELOSO & VELOSO LTDA",
    "SBJ1 - WASSOSNIKI E MELNISK LTDA",
    "52.755.177 - PAULO GERALDO PEREIRA DE FREITAS",
    "RJO7 - MARCIO BELCHIOR ALVES GONCALVES 07766180758",
    "LDB3 - M C FURTADO TRANSPORTES LTDA",
    "SJP3 - FUSION EXPRESS TRANSPORTES LTDA",
    "XAP3 - SABRINA DO NASCIMENTO LTDA",
    "SMS1 - WASSOSNIKI E MELNISK LTDA",
    "VCP2 - DHM LOG BRAZIL LTDA",
    "PGZ1 - 52.755.177 - PAULO GERALDO PEREIRA DE FREITAS",
    "SJK1 - FREE EXPRESS SJK LTDA",
    "QMF1 - TRANSPOELY LTDA",
    "IMP3 - P ROOSEVELT DOS REIS CAVALCANTE LTDA",
    "JCB3 - EVANDRO STRATMANN TRANSPORTES",
    "POA5 - TRANSQUEST TRANSPORTES LTDA",
    "POA6 - MABI LOGISTICA LTDA",
    "FEC2 - HF TRANSPORTES LTDA",
    "PMW2 - ROTEX LOGISTICA LTDA",
    "JOI5 - ANDERSON DANIEL MONTEIRO",
    "JOI4 - TRANSLURDES SERVIÇOS DE ENTREGA RAPIDA LTDA",
    "CFC1 - TRANSPORTES RODOVIARIOS ANELIZE LTDA",
    "SSZ3 - 37.868.310 FLAVIO ADRIANO DE MIRANDA",
    "SBS2 - MATHEUS MUHLBAUER 10555060985",
    "BSB3 - 36.210.422 WILLIAM DOS REIS MATOS",
    "FDS6 - V. TRANSPORTES LTDA",
    "REC4 - TRANSPORTADORA TEIXEIRA CARGO LTDA",
    "AJU4 - GTRANS LOG LOGISTICA E TRANSPORTES LTDA",
    "JPA4 - IAH TRANSPORTES E SERVIÇOS LTDA",
    "BRM2 - LINOS EXPRESS TRANSPORTES LTDA",
    "POA7 - CLAUDIO FOGACA DA SILVA",
    "JPA4 - HX SOLUÇÕES EM LOGISTICA",
    "POA10 - CRUZEIRO DO SUL LOGISTICA",
    "POA8 - DICAS ENCOMENDAS LTDA",
    "POA9 - D SANTOS LOGISTICA LTDA",
    "RAO4 - RP7 TRANSPORTES E LOGISTICA LTDA",
    "SAFRA TRR LTDA",
    "POA11 - TRANSPORTES CRUZEIRO DO SUL LTDA",
    "TRR2 - 3 R TRANSPORTE E LOGISTICA LTDA",
    "FRB2 - REDE PARANA EXPRESS SERVIÇOS DE ENTREGA LTDA",
    "RAO5 - F A MARTINS MACHADO TRANSPORTES",
    "CGB4 - QUALIDADE LOGISTICA E TRANSPORTES LTDA",
    "ARU3 - MARCEL HENRIQUE MASSON"
]

regional_GRU = [
    "GRU - CONECTA CARGO LOGISTICA INTEGRADA LTDA"
]

regional_BHZ = [
    "BHZ1 - HABIL LOG LTDA",
    "BHZ1 - HL TRANSPORTES EXPRESS EIRELI",
    "BHZ2 - LPK TRANSPORTES EIRELI",
    "BHZ3 - BOARETTO LOGISTICA LTDA",
    "CNF1 - LUCANO TRANSPORTES E CONSULTORIA EIRELI",
    "CVL2 - EXPRESSO MG LTDA",
    "CVL2 - LUCANO TRANSPORTES E LOGISTICA LTDA",
    "CVL3 - TIAGO ROBSON FONSECA 08116398601",
    "DIV1 - JLM TRANSPORTES E SERVIÇOS LTDA",
    "DIV2 - LPK TRANSPORTES LTDA - EPP",
    "DIV3 - ATUAL EXPRESS DIVINOPOLIS LTDA",
    "DIV3 - EDSON DALDEGAN DUARTE MARTINS CPF 12833668600",
    "GVR1 - GOLD LOGISTICA EM TRANSPORTES LTDA",
    "GVR2 - PRO ATIVA LOGISTICA LTDA",
    "GVR3 - 35.544.019 LUCIANA BRANDAO CARNEIRO",
    "GXP1 - MARCELINO JOSE DIAS MARTINS",
    "IPA1 - JOSE AMELIO PEREIRA DE MIRANDA",
    "JDF1 - NOVA ERA EXPRESS TRANSPORTES LTDA",
    "JDF2 - SEBASTIAO JORGE DA SILVA TRANSPORTES LTDA",
    "JDF3 - LUVIANA TRANSPORTES LTDA",
    "JML - JOAO BATISTA MORAIS EIRELI",
    "LAF1 - GAMP LOGISTICA",
    "LAF2 - SANDRO REZENDE MILITAO",
    "LAF3 - SAMUEL HENRIQUES DE FIGUEIREDO PINTO - TRANSPORTES URGENTES",
    "MAN1 - GAMP TRANSPORTES",
    "MAN2 - HSA TRANSPORTES E LOGISTICA LTDA",
    "MOC1 - TRANSELLO TRANSPORTES E LOGISTICA LTDA",
    "MOC2 - PONTUAL EXPRESS ENTREGAS RAPIDAS - MG LTDA",
    "MOC3 - SIGGA TRANSPORTES S/A",
    "NSE1 - LPK TRANSPORTES EIRELI",
    "NSE2 - EXPRESSO TITANIC TRANSPORTES LTDA",
    "OPT1 - JM EXPRESSO LTDA",
    "PAS1 - LPK TRANSPORTES EIRELI",
    "PAS2 - WAGNER HENRIQUE DA CRUZ DE ASSIS",
    "PPY1 - UNIDOS TRANSPORTES E TURISMO EIRELI",
    "PPY2 - LPK TRANSPORTES LTDA - EPP",
    "PTN1 - ARTHUR LUIS MIRANDA BAILON",
    "STL1 - 7L EXPRESS LTDA",
    "TFL1 - CERTO LOGISTICA LTDA",
    "TRC1 - MARCELINO JOSE DIAS MARTINS",
    "UDI1 - TRANSCAJURU LTDA",
    "VCS1 - GAMP TRANSPORTES",
    "VCS1 - ROTALOG TRANSPORTE E LOGÍSTICA LTDA.",
    "LAF4 - R M PEREIRA LOGISTICA E TRANSPORTE",
    "DIV4 - DR EXPRESS LTDA",
    "JML2 - POLLYANNA MENDES DUARTE",
    "MAN3 - JOSE GERALDO HOTT",
    "PPY4 - UNIDOS CARGAS SUL DE MINAS LTDA",
    "MAN4 - MINAS LOG LOGISTICA DE TRANSPORTE LTDA",
    "MOC6 - JLSINAI TRANSPORTES LTDA",
    "MOC5 - FERNANDO SOARES MOTA",
    "MOC4 - RAPIDO MONTES CLAROS TRANSPORTES LTDA",
    "PPY5 - TRIUNFO TRANSPORTES E ENCOMENDAS LTDA",
    "VAG2 - JT TRANSPORTES RODOVIARIO DE CARGAS LTDA",
    "BHZ - CONECTA CARGO LOGISTICA INTEGRADA LTDA"
]

regional_RJO = [
      "RJO1 - NOVA RIO CARGAS TRANSPORTE E LOGISTICA EIRELI",
      "RJO - CONECTA CARGO LOGISTICA INTEGRADA LTDA "
]