version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: db_dashboard_conecta
    environment:
      MYSQL_ROOT_PASSWORD: Conecta@2024
      MYSQL_DATABASE: db_dashboard_conecta
      MYSQL_USER: admin 
      MYSQL_PASSWORD: Conecta@2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
